### ISSUE TITLE
你好，我想问下这个能实现的的条件是用户的手机上必须有旧的安装包吧？

### ISSUE THREAD

**Issue by andansky** [smuyyh/IncrementallyUpdate#1]
你好，我想问下这个能实现的的条件是用户的手机上必须有旧的安装包吧？那如果用户已经装安装包删除了呢？现在很多安全软件一安装完都提示用户删除安装包呢

**Comment by smuyyh** [comment]
安装包可以在/data/app底下找到。代码也可以实现，通过getApplicationContext().getPackageResourcePath()可以获取APK路径，再提取出来。

**Comment by smuyyh** [comment]
提取旧版本APK代码已经上传~

**Comment by andansky** [comment]
你的意思是在app中提取安装包，而不是用户下载的安装包是吗？也就是说不存在安装包被用户删除而无法实现热更新的情况是这样的吗？

**Comment by smuyyh** [comment]
对的。不需要下载，如果要下载，那还不如直接更新了

**Comment by andansky** [comment]
蒽，好的。了解了，有空试试先。谢了啊~
