### ISSUE TITLE
生成so库的时候报错了。

### ISSUE THREAD

**Issue by fangfengfan** [smuyyh/IncrementallyUpdate#4]
我看了下Log是一些文件没有找到，麻烦你帮忙看下是不是漏传啦！
![o5qt38wz p 917 67ek2 i](https://cloud.githubusercontent.com/assets/16743022/23389432/e8410d2c-fda2-11e6-858b-8908343b6186.png)

**Comment by smuyyh** [comment]
有配置ndk环境么。

**Comment by fangfengfan** [comment]
有配置的。
![i6a30 lolyymqk 5 q el](https://cloud.githubusercontent.com/assets/16743022/23389719/da2ca1b8-fda4-11e6-9f22-028c0d643f0c.png)

**Comment by fangfengfan** [comment]
电脑的环境变量也配置好了的
![6 55i8 j_oa1_une6yb mc1](https://cloud.githubusercontent.com/assets/16743022/23389808/4e638128-fda5-11e6-9c7a-7edfbfe1313a.png)

**Comment by smuyyh** [comment]
这个看起来还是你的静态库找不到。 检查检查 看哪里没配好。比如NDK 64位 要和系统的一样。文件没漏传，还是你环境的问题。

**Comment by fangfengfan** [comment]
好的，我检查下

**Comment by fangfengfan** [comment]
你好，我发现了有很多这样的打印错误Log的文件找不到，我注释掉就可以编译出so文件，运行没有问题。
![rj 8_ 1 f4 x 86hn pl_u](https://cloud.githubusercontent.com/assets/16743022/23536693/a59b3fc2-0001-11e7-86ee-7b9c09233c89.png)

**Comment by smuyyh** [comment]
err.h 头文件是在ndk目录下的。

2017-03-03 11:08 GMT+08:00 fangfengfan <notifications@github.com>:

**Comment by fangfengfan** [comment]
那估计我的ndk里面就没有这个东西了，我注释掉应该没多大的关系吧？

**Comment by smuyyh** [comment]
这个主要是用于打印一些错误日志信息。 没多大关系

**Comment by fangfengfan** [comment]
OK.....Thanks.
